flags: 
  train_flag : False
  save_plot_flag : False
paths: 
  train_path : "/home/argus-vision/vision/RC_Playground/RCnet/datasets/train"
  test_path : "/home/argus-vision/vision/RC_Playground/RCnet/datasets/test"
  val_path: "/home/argus-vision/vision/RC_Playground/RCnet/datasets/val" 
  # train_path : "/home/argus-vision/vision/RC_Playground/RCnet/data/train2"
  # test_path : "/home/argus-vision/vision/RC_Playground/RCnet/data/test2"
  # val_path: "/home/argus-vision/vision/RC_Playground/RCnet/data/val2" 

  model_save_path : "/home/argus-vision/vision/RC_Playground/RCnet/model/model.pth"
  model_load_path : "/home/argus-vision/vision/RC_Playground/RCnet/model/model.pth"
  save_plot_path : "/home/argus-vision/vision/RC_Playground/RCnet/results/loss_vs_epoch.png"
  
hyperparameters:
  learning_rate : 0.0001
  epochs : 50
